//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materiales_Hernandez_V2.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotización
    {
        public int IdCotizacion { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Condiciones { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Cliente Clientes { get; set; }
        public virtual Empleado Empleadoes { get; set; }
    }
}
