//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materiales_Hernandez_V2.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Cotización = new HashSet<Cotización>();
        }
    
        public int IdEmpleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cargo { get; set; }
        public string FechaIngreso { get; set; }
    
        public virtual ICollection<Cotización> Cotización { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Comprobante Comprobante { get; set; }
    }
}
