//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materiales_Hernandez_V2.Services.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Comprobantes = new HashSet<Comprobante>();
            this.Cotización = new HashSet<Cotización>();
            this.Pedidoes = new HashSet<Pedido>();
        }
    
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public double PrecioVenta { get; set; }
        public int Stock { get; set; }
    
        public virtual ICollection<Comprobante> Comprobantes { get; set; }
        public virtual ICollection<Cotización> Cotización { get; set; }
        public virtual ICollection<Pedido> Pedidoes { get; set; }
    }
}
